### ISSUE TITLE
do/while && vs. ||

### ISSUE THREAD

**Issue by GoPapaSmurf** [christophe-mommer/eni-begin-csharp#13]
p.132, dernière ligne du code tout en bas de la page (corrigé de l'exercice en algorithmique), il y a un petit problème dans la boucle do/while. Elle utilise un ET logique, alors qu'elle devrait utiliser un OU logique : 

Avant : 
```
int borneMaximum = 0;
string saisie = string.Empty;
do {
	Console.WriteLine("Saissez la borne maximum du chiffre à deviner : ");
	saisie = Console.ReadLine();
	if(saisie == "q"){
		Environment.Exit(0);
	}
} while(!int.TryParse(saisie, out borneMaximum) && borneMaximum <= 0);
```

Après : 
```
int borneMaximum = 0;
string saisie = string.Empty;
do {
	Console.WriteLine("Saissez la borne maximum du chiffre à deviner : ");
	saisie = Console.ReadLine();
	if(saisie == "q"){
		Environment.Exit(0);
	}
} while(!int.TryParse(saisie, out borneMaximum) || borneMaximum <= 0);
```

**Comment by christophe-mommer** [comment]
Oula, la petite coquille vicieuse !
C'est corrigé !

**Comment by GoPapaSmurf** [comment]
> Oula, la petite coquille vicieuse ! C'est corrigé !

Merci, je viens à l'instant de voir que le code est repris en p.144 (avec l'erreur)
