### ISSUE TITLE
ElementAtOrDefault(0)

### ISSUE THREAD

**Issue by GoPapaSmurf** [christophe-mommer/eni-begin-csharp#14]
p.164, chapitre 5 sur LINQ, avant-dernière ligne de code. Cette ligne devait tester la méthode `ElementAtOrDefault()` : 

Avant :
`var premierDefaut = entiers.Where(i => i > 5).ElementAt(0);`

Après :
`var premierDefaut = entiers.Where(i => i > 5).ElementAtOrDefault(0);`

**Comment by christophe-mommer** [comment]
Bien vu, c'est corrigé, j'étais justement dessus !
