### ISSUE TITLE
Suggestion : Explication sur ce qu'est une propriété décorée

### ISSUE THREAD

**Issue by GoPapaSmurf** [christophe-mommer/eni-begin-csharp#19]
p.196, chapitre 6 sur la sérialisation, section 4.3 JsonSerializer.
À à peu près un tiers de la page, il est précisé :

> `JsonIgnore` afin d’indiquer qu’on ne souhaite pas traiter la propriété décorée.

Je pense qu'il serait intéressant d'expliquer succinctement ce qu'est une propriété décorée. Je propose :

> `JsonIgnore` afin d’indiquer qu’on ne souhaite pas traiter la propriété décorée (c'est-à-dire la propriété si celle-ci est précédée de l'attribut **`[JsonIgnore]`**).

**Comment by christophe-mommer** [comment]
J'ai reformulé
