### ISSUE TITLE
Erreurs de texte

### ISSUE THREAD

**Issue by christophe-mommer** [christophe-mommer/eni-begin-csharp#2]
Page 121, chapitre 4 : utilisation du caractère ":" au lieu de ";" en fin de ligne pour `LastIndexOf`

**Comment by GoPapaSmurf** [comment]
Page 27, chapitre 2 : Emploi du terme "objet" au lieu du terme "classe" à trois endroits :

> On récupère _l'objet_ Console

> On récupère la méthode WriteLine sur _l'objet_ Console

> ...cette instruction consiste simplement en l'appel d'une méthode sur _un objet_ déjà existant.

Si doute, il y a, sur la terminologie, voici quelques références:

Dans le livre "C#10 in a Nutshell", de Joseph Albahari :

 - [p.58](https://books.google.fr/books?id=9iJdEAAAQBAJ&pg=PT39&lpg=PT39&dq=%22its+type,+you+specify+its+type+name+rather+than+an+instance.+An+example+is%22&source=bl&ots=e-ZLFm5Y-S&sig=ACfU3U3SJg71Aj_2YHCQa7hO60nt8LTcig&hl=fr&sa=X&ved=2ahUKEwi_vJXU4uf5AhWJwIUKHZNXAMMQ6AF6BAgFEAM#v=onepage&q=%22its%20type%2C%20you%20specify%20its%20type%20name%20rather%20than%20an%20instance.%20An%20example%20is%22&f=false), section "Instance versus static members" :
> To refer to a static member from outside its type, you specify its type name **rather than an instance**. An example is the WriteLine method of the **Console class**. Because this is static, we call Console.WriteLine() and not new Console().WriteLine(). (The Console class is actually declared **as a static class**, which means that all of its members are static, and **you can never create instances of a Console**.)

 - [p.169](https://books.google.fr/books?id=4CJdEAAAQBAJ&pg=PA112&lpg=PA112&dq=%22A+class+marked+static+cannot+be+instantiated+or+subclassed,+and+must+be%22&source=bl&ots=70XnhIn1_G&sig=ACfU3U35DnaKK-GqMR8JjauAO68nfRODdA&hl=fr&sa=X&ved=2ahUKEwjo3_CP5Of5AhVLxYUKHYEHBfYQ6AF6BAgCEAM#v=onepage&q=%22A%20class%20marked%20static%20cannot%20be%20instantiated%20or%20subclassed%2C%20and%20must%20be%22&f=false), section "Static classes" :
> A class marked static **cannot be instantiated** or subclassed, and must be composed solely of static members. The **System.Console** and System.Math classes are good examples of **static classes**.

 - [p.43](https://www.oreilly.com/library/view/c-10-in/9781098121945/ch01.html), section "What’s New in C# 6.0": 
> The using static (see “Namespaces”) directive lets you import all the static members of a type so that you can use those members unqualified :
```
using static System.Console;
WriteLine ("Hello, world");
```

 - [p.138](https://books.google.fr/books?id=4CJdEAAAQBAJ&pg=PA89&lpg=PA89&dq=%22The+using+static+directive+imports+a+type+rather+than+a+namespace.+All+static+members+of+the+imported+type+can+then+be+used+without+qualification.%22&source=bl&ots=70XnhIn0UJ&sig=ACfU3U1Pos2BDuVwCHc9wodXeal1DtHdPw&hl=fr&sa=X&ved=2ahUKEwjE-9fE4-f5AhVwgc4BHf_gCGsQ6AF6BAgDEAM#v=onepage&q=%22The%20using%20static%20directive%20imports%20a%20type%20rather%20than%20a%20namespace.%20All%20static%20members%20of%20the%20imported%20type%20can%20then%20be%20used%20without%20qualification.%22&f=false), section "using static" :
> The using static directive imports a type rather than a namespace. All static members of the imported type can then be used without qualification. In the following example, we call **the Console class’s static WriteLine method** without needing to refer to the type:
```
using static System.Console;
WriteLine ("Hello");
```

Dans le livre "C# 10 and .NET 6", de Mark J. Price :
 - [p.84-85](https://books.google.fr/books?id=OyNMEAAAQBAJ&pg=PA84&lpg=PA84&dq=%22type+name+throughout+our+code.+You+can+use+your+code+editor%27s+find+and+replace+feature+to%22&source=bl&ots=cNQ67OnlGz&sig=ACfU3U3PSsH_-mJ6zKYAClR8_ZH2Solcew&hl=fr&sa=X&ved=2ahUKEwjB47rW3-f5AhUF-BoKHWBJB2kQ6AF6BAgCEAM#v=onepage&q&f=false), section "Simplifying the usage of the console":
> the System.Console **class**

**Comment by GoPapaSmurf** [comment]
p.31, section 2.1.1, les intervalles de valeurs possibles pour chaque type numérique (colonne de droite) sont affichés avec des chiffres en indices au lieu d'exposants. Par exemple "2 indice 7" au lieu de "2 puissance 7".

**Comment by GoPapaSmurf** [comment]
p.33, section 2.1.2, l'exemple utilise un caractère spécial dans le nom de la variable avec un accent circonflexe :
`string chaîne = "chaîne";`
Par interdit en soi, mais c'est mieux sans.

**Comment by GoPapaSmurf** [comment]
p.38, section 2.2.1, les minutes de l'énoncé dont différentes de celles du code (19h59 vs. 19h50).

**Comment by GoPapaSmurf** [comment]
p.59, section 1.1.1, première étape, il y a une inversion des mots "où" et "vous" :
> Placez-vous sur le dossier **vous où** souhaitez créer la nouvelle classe.

**Comment by GoPapaSmurf** [comment]
p.104, 2° paragraphe, formulation redondante :

> on peut avoir ~~uniquement~~ une seule instruction ```if```

**Comment by GoPapaSmurf** [comment]
p.173, chapitre 5 sur LINQ, section "5. Exercice" : 

> Il est temps de mettre en pratique ce qui a été vu dans ~de~ ce chapitre sur LINQ.

**Comment by christophe-mommer** [comment]
> Page 27, chapitre 2 : Emploi du terme "objet" au lieu du terme "classe" à trois endroits :
> 
> > On récupère _l'objet_ Console
> 
> > On récupère la méthode WriteLine sur _l'objet_ Console
> 
> > ...cette instruction consiste simplement en l'appel d'une méthode sur _un objet_ déjà existant.
> 
> Si doute, il y a, sur la terminologie, voici quelques références:
> 
> Dans le livre "C#10 in a Nutshell", de Joseph Albahari :
> 
> * [p.58](https://books.google.fr/books?id=9iJdEAAAQBAJ&pg=PT39&lpg=PT39&dq=%22its+type,+you+specify+its+type+name+rather+than+an+instance.+An+example+is%22&source=bl&ots=e-ZLFm5Y-S&sig=ACfU3U3SJg71Aj_2YHCQa7hO60nt8LTcig&hl=fr&sa=X&ved=2ahUKEwi_vJXU4uf5AhWJwIUKHZNXAMMQ6AF6BAgFEAM#v=onepage&q=%22its%20type%2C%20you%20specify%20its%20type%20name%20rather%20than%20an%20instance.%20An%20example%20is%22&f=false), section "Instance versus static members" :
> 
> > To refer to a static member from outside its type, you specify its type name **rather than an instance**. An example is the WriteLine method of the **Console class**. Because this is static, we call Console.WriteLine() and not new Console().WriteLine(). (The Console class is actually declared **as a static class**, which means that all of its members are static, and **you can never create instances of a Console**.)
> 
> * [p.169](https://books.google.fr/books?id=4CJdEAAAQBAJ&pg=PA112&lpg=PA112&dq=%22A+class+marked+static+cannot+be+instantiated+or+subclassed,+and+must+be%22&source=bl&ots=70XnhIn1_G&sig=ACfU3U35DnaKK-GqMR8JjauAO68nfRODdA&hl=fr&sa=X&ved=2ahUKEwjo3_CP5Of5AhVLxYUKHYEHBfYQ6AF6BAgCEAM#v=onepage&q=%22A%20class%20marked%20static%20cannot%20be%20instantiated%20or%20subclassed%2C%20and%20must%20be%22&f=false), section "Static classes" :
> 
> > A class marked static **cannot be instantiated** or subclassed, and must be composed solely of static members. The **System.Console** and System.Math classes are good examples of **static classes**.
> 
> * [p.43](https://www.oreilly.com/library/view/c-10-in/9781098121945/ch01.html), section "What’s New in C# 6.0":
> 
> > The using static (see “Namespaces”) directive lets you import all the static members of a type so that you can use those members unqualified :
> 
> ```
> using static System.Console;
> WriteLine ("Hello, world");
> ```
> 
> * [p.138](https://books.google.fr/books?id=4CJdEAAAQBAJ&pg=PA89&lpg=PA89&dq=%22The+using+static+directive+imports+a+type+rather+than+a+namespace.+All+static+members+of+the+imported+type+can+then+be+used+without+qualification.%22&source=bl&ots=70XnhIn0UJ&sig=ACfU3U1Pos2BDuVwCHc9wodXeal1DtHdPw&hl=fr&sa=X&ved=2ahUKEwjE-9fE4-f5AhVwgc4BHf_gCGsQ6AF6BAgDEAM#v=onepage&q=%22The%20using%20static%20directive%20imports%20a%20type%20rather%20than%20a%20namespace.%20All%20static%20members%20of%20the%20imported%20type%20can%20then%20be%20used%20without%20qualification.%22&f=false), section "using static" :
> 
> > The using static directive imports a type rather than a namespace. All static members of the imported type can then be used without qualification. In the following example, we call **the Console class’s static WriteLine method** without needing to refer to the type:
> 
> ```
> using static System.Console;
> WriteLine ("Hello");
> ```
> 
> Dans le livre "C# 10 and .NET 6", de Mark J. Price :
> 
> * [p.84-85](https://books.google.fr/books?id=OyNMEAAAQBAJ&pg=PA84&lpg=PA84&dq=%22type+name+throughout+our+code.+You+can+use+your+code+editor%27s+find+and+replace+feature+to%22&source=bl&ots=cNQ67OnlGz&sig=ACfU3U3PSsH_-mJ6zKYAClR8_ZH2Solcew&hl=fr&sa=X&ved=2ahUKEwjB47rW3-f5AhUF-BoKHWBJB2kQ6AF6BAgCEAM#v=onepage&q&f=false), section "Simplifying the usage of the console":
> 
> > the System.Console **class**

Corrigé

**Comment by christophe-mommer** [comment]
> p.31, section 2.1.1, les intervalles de valeurs possibles pour chaque type numérique (colonne de droite) sont affichés avec des chiffres en indices au lieu d'exposants. Par exemple "27" au lieu de "27".

Corrigé, même si en vrai, c'est ENI qui a fait ça, je verrai dans les mansucrits finaux s'ils ont remis le couvert, dans le doc Word c'est OK

**Comment by christophe-mommer** [comment]
> p.33, section 2.1.2, l'exemple utilise un caractère spécial dans le nom de la variable avec un accent circonflexe : `string chaîne = "chaîne";` Par interdit en soi, mais c'est mieux sans.

Je l'ai corrigé dans le doc Word. Ce doit être leur système de correction automatique qui a provoqué cela, je serai vigilant sur les manuscrits finaux

**Comment by christophe-mommer** [comment]
> p.38, section 2.2.1, les minutes de l'énoncé sont différentes de celles du code (19h59 vs. 19h50).

Bien vu, c'est corrigé

**Comment by christophe-mommer** [comment]
> 

Pas vraiment. Le but du paragraphe est d'expliquer les combinaisons possibles :
Soit seulement un if
Soit un if / else
Soit un if, plusieurs else if, et un else final

**Comment by christophe-mommer** [comment]
> p.173, chapitre 5 sur LINQ, section "5. Exercice" :
> 
> > Il est temps de mettre en pratique ce qui a été vu dans ~de~ ce chapitre sur LINQ.

Corrigé

**Comment by GoPapaSmurf** [comment]
p.79, chapitre 3 sur la P.O.O., section 2.1.3, il manque un `e` à `central` à la dernière ligne : 
```
var centrale = new CentraleOrdinateurs();
var mac = new Mac();
central.DemarrerOrdinateurPrincipal(mac);
```

**Comment by christophe-mommer** [comment]
> p.79, chapitre 3 sur la P.O.O., section 2.1.3, il manque un `e` à `central` à la dernière ligne :
> 
> ```
> var centrale = new CentraleOrdinateurs();
> var mac = new Mac();
> central.DemarrerOrdinateurPrincipal(mac);
> ```

Bien vu, j'étais complètement passé à côté !

**Comment by GoPapaSmurf** [comment]
p.113, chapitre 4 sur l'algorithmique, la portion de code, tout en bas, qui donne une vision du _switch expression_ : je pense qu'on pourrait la compléter en attribuant le résultat à une variable (c'est ce qui est fait quand on utilise un _switch expression_), on pourrait enlever l'accent aigu à `étiquette`, ajouter 2 autres étiquettes pour montrer que c'est possible d'en tester plusieurs, et on pourrait ajouter un point-virgule à la fin (ce qui le distingue du _switch statement_). Suggestion :
Avant : 
`variable switch
{
	étiquette => instruction
}`

Après :
`var destination = variableTestee switch {
    etiquette1 => instruction1,
    etiquette2 => instruction2,
    etiquette3 => instruction3
}; `

**Comment by GoPapaSmurf** [comment]
p.114, chapitre 4 sur l'algorithmique, la portion de code de la fonction `EstQuelType(Vehicule v)` comporte 3 variables qui posent problème dans ce code :

```
public void EstQuelType(Vehicule v) {
	var typeVehicule = obj switch {
		Voiture v => "C'est une voiture de marque " + c.Marque,
		Camion _ => "C'est un camion",
		_ => "Type non reconnu"
	};
}
```

- `obj` n'a pas été déclaré
- `Voiture v` du switch expression a déjà été déclarée un cran plus haut
- `c.Marque` n'a pas été déclarée

On pourrait modifier cette fonction pour qu'elle imprime le type de véhicule dans la console, ou qu'elle retourne une valeur sous forme de chaîne de caractères. Voici ce que je propose : 

```
public static string EstQuelType(Vehicule v){
	var typeVehicule = v switch {
		Voiture voiture => "C'est une voiture de marque " + voiture.Marque,
		Camion _ => "C'est un camion",
		_ => "Type non reconnu"
	};
	return typeVehicule;
}
```

J'ai mis la fonction comme statique car elle prend un objet en paramètre, mais on n'est pas obligé, on peut aussi faire en sorte qu'elle soit la méthode d'une instance 😉

**Comment by GoPapaSmurf** [comment]
p.118, chapitre 4 sur l'algorithmique, milieu du §3, en milieu de page : 
> séparées par deux-points

Il faudrait enlever le trait d'union car ça pourrait prêter à confusion à la première lecture (on pourrait penser à un deux-points) 😉

**Comment by GoPapaSmurf** [comment]
p.127, chapitre 4 sur l'algorithmique, dernier paragraphe: 

> les valeurs de la boucle de `for`

Suggestion, supprimer le "de" :

> les valeurs de la boucle `for`

**Comment by GoPapaSmurf** [comment]
p.150, Chapitre 5 sur LINQ, avant-dernier paragraphe, tout en bas : ajout d'un "s" à "voiture"

> ...pour récupérer tout une liste de voiture filtrées

Suggestion :

> ...pour récupérer tout une liste de voitures filtrées

**Comment by GoPapaSmurf** [comment]
p.167, chapitre 5 sur LINQ, petite remarque sans grande importance, mais le code du livre qui utilise la méthode `Average()` retourne chez moi 13,4 (alors que dans dans le livre c'est 13,2). J'ai essayé dans Visual Studio Code et LINQPad.
Code : 
```
public class Etudiant 
{ 
    public string Nom { get; set; } 
    public int MoyenneSur20 { get; set; } 
} 
 
var etudiantsMoyenne = new List<Etudiant> 
{ 
    new Etudiant{ Nom = "Bob", MoyenneSur20 = 14}, 
    new Etudiant{ Nom = "Jim", MoyenneSur20 = 15}, 
    new Etudiant{ Nom = "Jack", MoyenneSur20 = 12}, 
    new Etudiant{ Nom = "John", MoyenneSur20 = 13}, 
    new Etudiant{ Nom = "Tim", MoyenneSur20 = 13}, 
}; 
 
var moyenneDesMoyennes = etudiantsMoyenne.Average(e => e.MoyenneSur20);
```

**Comment by GoPapaSmurf** [comment]
p.168, chapitre sur LINQ, deux dernières lignes de code tout en bas de la page : `SequenceEqual()` s'applique à une variable `entiers1`, au lieu de `entiers` :

Avant :
```
var equal = entiers1.SequenceEqual(entiersEq); // true 
var notEqual = entiers1.SequenceEqual(entiersNotEq); // false 
```

Après :
```
var equal = entiers.SequenceEqual(entiersEq); // true 
var notEqual = entiers.SequenceEqual(entiersNotEq); // false 
```

**Comment by GoPapaSmurf** [comment]
p.194, chapitre 6 sur la sérialisation, section 4.2 JsonDocument.
Dans le code tout en bas de la page, il manque un point-virgule à la fin de la ligne qui commence par `string rue` :

`string rue = doc.RootElement.GetProperty("Adresse").GetProperty("Rue").GetString()`

**Comment by GoPapaSmurf** [comment]
p.210, chapitre 7 Concepts avancés, petite erreur de casse sur le nom de la variable :

Avant:
`Result.Add(i);`

Après:
`result.Add(i);`

**Comment by GoPapaSmurf** [comment]
p.211, chapitre 7 Concepts avancés, petite faute de frappe sur le nom de l'interface : 
Avant:
`public async IAsyncIEnumerable<int> GetInts() { ... }`

Après:
`public async IAsyncEnumerable<int> GetInts() { ... }`

**Comment by GoPapaSmurf** [comment]
p.211, chapitre 7 Concepts avancés, petite oubli d'une parenthèse fermante dans le `foreach` :

Avant:
`await foreach(var i in GetInts() { ... }`

Après:
`await foreach(var i in GetInts()) { ... }`

**Comment by GoPapaSmurf** [comment]
p.213, chapitre 7 Concepts avancés, section 2.1.1 sur les _delegates_, en milieu de page, petite erreur de casse sur le modificateur d'accès `public` :

`Public delegate void MonDelegueVoidSansParametres();`

**Comment by GoPapaSmurf** [comment]
p.213-216, chapitre 7 Concepts avancés, sections 2.1.1 sur les delegates et 2.1.2 sur les events.
À partir de la page 213, les exemples de code mentionnent un ancien chapitre (_Chap5_) lors du nommage des classes, au lieu d'utiliser le préfixe _Chap7_, qui est le chapitre en cours. J'ai relevé cette incohérence mineure à ces endroits-là :

p.213, tout en bas : `public class Chap5Delegates`
p.214, milieu de page : `public class Chap5Delegates`
p.215, milieu de page : `public class Chap5Delegates`
p.215, un peu plus bas, à nouveau : `public class Chap5Delegates`
p.216, vers le haut : `public class Chap5EventSubscriber`
p.216, un peu plus bas : `var producer = new Chap5Delegates()`

Dans mes prises de notes, pour les events, j'ai renommé les classes comme ça :
- `Chap5Delegates` -> `Emetteur`
- `Chap5EventSubscriber` -> `Recepteur`

Ça pourrait être plus parlant. Ce n'est qu'une suggestion.

**Comment by GoPapaSmurf** [comment]
p.243, chapitre 8 Créer des applications, à propos des applications ASP.NET MVC, 3° paragraphe en milieu de page, il manque "de" :
> il s’agit de la seconde partie l’URL

**Comment by GoPapaSmurf** [comment]
L'avertissement mineur ci-dessus est aussi présent dans le code suivant p.250 :
`public string Date { get; set; }`

Message de l'IDE :
> Le propriété 'Date' non-nullable doit contenir une valeur non-null lors de la fermeture du constructeur. Envisagez de déclarer le propriété comme nullable. [RazorPages]csharp(CS8618)

Suggestion:
`public string? Date { get; set; }`

**Comment by GoPapaSmurf** [comment]
p.266, chapitre 8 Créer des applications, à propos des applications WinForms : le raccourci clavier pour afficher la boîte à outils n'est pas `[Ctrl] W, X` mais `Ctrl-Alt-X`.

**Comment by GoPapaSmurf** [comment]
p.291, chapitre 9 Référence :
À la ligne `decimal`, l'intervalle de valeurs a une petite erreur au niveau du signe ± :

> decimal : ± -10<sup>28</sup> à ± 10<sup>28</sup>

Suggestion :
> decimal : -10<sup>28</sup> à +10<sup>28</sup>

Ou bien :
> decimal : ± 10<sup>28</sup>

**Comment by GoPapaSmurf** [comment]
> > p.31, section 2.1.1, les intervalles de valeurs possibles pour chaque type numérique (colonne de droite) sont affichés avec des chiffres en indices au lieu d'exposants. Par exemple "2<sub>7</sub>" au lieu de "2<sup>7</sup>".
> 
> Corrigé, même si en vrai, c'est ENI qui a fait ça, je verrai dans les manuscrits finaux s'ils ont remis le couvert, dans le doc Word c'est OK

Merci. Dans le chapitre 9 Références, à différents endroits aussi, les nombres en exposants sont mis en indices à la place (p.291, 292 et 293).

**Comment by GoPapaSmurf** [comment]
p.292, chapitre 9 Référence, petite faute de frappe au nom de la valeur :

`sbyte moinDix = -10;`

**Comment by GoPapaSmurf** [comment]
p.295, chapitre 9 Référence, on pourrait ajouter les accolades à la définition de l'interface :

> `public interface IMonInterface`

Suggestion : `public interface IMonInterface {  }`
