### ISSUE TITLE
Possible contradiction dans l'explication de l'asynchronisme

### ISSUE THREAD

**Issue by GoPapaSmurf** [christophe-mommer/eni-begin-csharp#22]
p.203-204, chapitre 7 Concepts avancés sur le fonctionnement de base de l'asynchronisme.
L'explication de l'asynchronisme semble être contradictoire :

> Lorsque qu’on lance une machine pour laver son linge, celle-ci effectue son travail de façon asynchrone par rapport à soi-même, **ce qui permet, pendant ce temps, de s’occuper à faire autre chose**.

Et 

> Dès lors que qu’on met le linge dans la machine et qu’on la lance, on délègue du travail appliqué à ce linge à une autre entité que soi-même. **Lorsque ce travail est terminé, on peut reprendre son propre travail**.

J'ai l'impression que le premier paragraphe explique qu'on peut faire autre chose pendant que la machine travaille, alors que le deuxième paragraphe explique qu'on doit attendre que la machine ait terminé pour pouvoir faire autre chose.

**Comment by christophe-mommer** [comment]
C'est vrai que ça peut porter à confusion, j'ai retravaillé le paragraphe
