### ISSUE TITLE
Fonctionnement des combinaisons de valeurs dans les énumérations

### ISSUE THREAD

**Issue by GoPapaSmurf** [christophe-mommer/eni-begin-csharp#7]
En p.90, section 2.2.5 sur les énumérations, il faudrait davantage expliquer le fonctionnement des combinaisons de valeurs. Il m'a fallu du temps pour comprendre le principe. Dans l'exemple de code du livre, par exemple, expliquer pourquoi changer l'indice de ```SSD``` pour une valeur impaire, telle que ```3```, fait que ```possedeUnSSD``` retourne ```true``` même si ```capacite``` ne contient pas de flag ```CapaciteMaterielle.SSD```.

```
CapaciteMaterielle capacite = CapaciteMaterielle.Clavier | CapaciteMaterielle.Souris | CapaciteMaterielle.Ecran;
var possedeUnSSD = capacite.HasFlag(CapaciteMaterielle.SSD);
Console.Write(possedeUnSSD);   //   Retourne false

[Flags]
public enum CapaciteMaterielle
{
	Clavier = 0,
	Souris = 1,
	Ecran = 2,
	SSD = 4,   //   **Si SSD = 3, possedeUnSSD == true (!)**
	WebCam = 8
}
```

Si on modifie l'exemple du livre pour tester la présence d'un clavier dans la liste, celui-ci ayant l'indice ```0``` (multiple de 2), même si le clavier ne figure pas dans la liste de matériel, le test retourne ```true``` : 

```
CapaciteMaterielle capacite = CapaciteMaterielle.Souris | CapaciteMaterielle.Ecran;
var possedeUnClavier = capacite.HasFlag(CapaciteMaterielle.Clavier);
Console.Write(possedeUnClavier);   //   Retourne true

[Flags]
public enum CapaciteMaterielle
{
	Clavier = 0,
	Souris = 1,
	Ecran = 2,
	SSD = 4,
	WebCam = 8
}
``` 

L'explication du livre ajoute que : 

> Afin que cela soit réalisable, chaque valeur doit impérativement être un multiple de 2

Les indices ne sont pas tous des multiples de 2 dans l'exemple (la souris a la valeur 1).

**Comment by christophe-mommer** [comment]
Étant donné que cela a avoir avec le calcul binaire, j'ai largement enrichi le chapitre pour expliquer comment fonctionne le binaire et les masques binaires afin que cet exemple soit compréhensible.
En effet, il y avait une erreur, il ne s'agit pas de multiple de 2, mais bien de puissance de 2.
