### ISSUE TITLE
AsEnumerable(); ne modifie pas le type en IEnumerable dans l'exemple du livre

### ISSUE THREAD

**Issue by GoPapaSmurf** [christophe-mommer/eni-begin-csharp#8]
Dans le chapitre 5 sur LINQ, section 3.1, à la p.162, la méthode ```AsEnumerable();``` ne convertit pas le type ```IOrderedEnumerable``` en ```IEnumerable``` dans l'exemple du livre : 
```
var entiers = new List<int> {1, 2, 3, 4, 5 }; 
var entiersDecroissants = entiers.OrderByDescending(e => e).AsEnumerable();
```
Avec ou sans ```.AsEnumerable()```, la commande ```Console.Write(entiersDecroissants.GetType());``` retourne toujours le même type : 

```System.Linq.OrderedEnumerable`2[System.Int32,System.Int32]```

**Comment by christophe-mommer** [comment]
J'ai rajouté une explication sur l'usage de AsEnumerable pour clarifier le point
