### ISSUE TITLE
Quiz : Différence requêtes LINQ méthodes d’extension vs. expression de requête

### ISSUE THREAD

**Issue by GoPapaSmurf** [christophe-mommer/eni-begin-csharp#9]
Sur le quiz en ligne du site d'ENI Editions, correspondant au chapitre 5 sur ```LINQ```, après relecture et vérification, il semble y avoir une erreur dans une des questions :

> Dans la liste ci-dessous, quelle est la principale différence entre les requêtes LINQ sous forme de méthodes d’extension et celles faites avec l’expression de requête ?
> ❌ Les méthodes d’extension contiennent moins d’opérateurs que l’expression de requête
> ✔️ Les méthodes d’extension contiennent plus d’opérateurs que l’expression de requête

Dans le livre, les méthodes d’extension ont pourtant moins d’opérateurs que les expressions de requêtes, n'est-ce pas ? Par ex : 
```
var divisibleParSept = entiers.Where(e => e % 7 == 0); 
var divisibleParSeptInline = from e in entiers where e % 7 == 0 select e; 
```

**Comment by cdie** [comment]
Non, c'est que la question est mal formulée.
Ici, le but étant de dire qu'il y a + d'opérateurs LINQ avec les méthodes d'extensions (comprendre par-là, + de possibilités)

**Comment by GoPapaSmurf** [comment]
Plus de possibilités, OK, je comprends, oui, je suis d'accord.
